AppEntrega/urls.py
from django.urls import path
from . import views

app_name = 'AppEntrega'

urlpatterns = [
    path('profesores/', views.profesores, name='profesores'),
    path('socios/', views.socios, name='socios'),
    path('deportes/', views.deportes, name='deportes'),
    
    path('', views.inicio, name='inicio'),
    path('form/profesor/', views.postProfesor, name='profeFormulario'),
    path('form/socio/', views.postSocio, name='socioFormulario'),
    path('form/deporte/', views.postDeporte, name='deporteFormulario'),
    path('deporte/', views.getDeporte, name='getDeporte'),
]

Entrega1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppEntrega/', include('AppEntrega.urls')),
    
]

AppEntrega/models.py
from django.db import models

# Create your models here.
class Deportes(models.Model):
    nombre = models.CharField(max_length= 50)
    turno = models.CharField(max_length=50)
    comision = models.IntegerField()

    def __str__(self):
        return self.nombre+" "+self.turno

class Profesores(models.Model):
    nombre = models.CharField(max_length = 30)
    apellido = models.CharField(max_length = 30)
    email = models.EmailField()
    profesion = models.CharField(max_length = 30)

class Socios(models.Model):
    nombre = models.CharField(max_length = 30)
    apellido = models.CharField(max_length = 30)
    dni= models.IntegerField()
    email = models.EmailField()

AppEntrega/forms.py
from django import forms


class formDeporte(forms.Form):
    nombre = forms.CharField()
    turno = forms.CharField()
    comision = forms.IntegerField()


class formProfesor(forms.Form):
    nombre = forms.CharField()
    apellido = forms.CharField()
    email = forms.EmailField()
    profesion = forms.CharField()

class formSocio(forms.Form):
    nombre = forms.CharField()
    apellido = forms.CharField()
    email = forms.EmailField()
    dni = forms.IntegerField()
    

AppEntrega/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Deportes, Profesores, Socios
from AppEntrega.forms import formDeporte, formProfesor, formSocio

# Create your views here.


def inicio(request):
    return render(request, "Appentrega/inicio.html")


def profesores(request):
    profesores = Profesores.objects.all()
    return render(request, "Appentrega/profesores.html", {"profesores": profesores})


def socios(request):
    socios = Socios.objects.all()
    return render(request, "Appentrega/socios.html", {"socios": socios})

def deportes(request):
    deportes = Deportes.objects.all()
    return render(request, "Appentrega/deportes.html", {"deportes": deportes})


def getDeporte(request):
    if request.GET["deporte"]:
        depor = request.GET["deporte"]
        deporte = Deportes.objects.filter(nombre = depor)
        if len(deporte) != 0:
            return render(request, "Appentrega/deportes.html", {"deportes": deporte})
        else:
            return render(request, "Appentrega/deportes.html", {"mensaje": "No se encontraron deportes"})
    else:
        return redirect("AppEntrega:deportes")


def postDeporte(request):
    if request.method == "POST":
        form = formDeporte(request.POST)
        if form.is_valid():
            info = form.cleaned_data
            nombre = info["nombre"]
            turno = info["turno"]
            comision = info["comision"]
            deporte = Deportes(nombre=nombre, turno=turno, comision=comision)
            deporte.save()
            return redirect("AppEntrega:deportes")
        else:
            return render(request, "Appentrega/deportes.html", {"mensaje": "Error"})
    else:
        form = formDeporte()
    return render(request, "Appentrega/deportes.html", {"formulario": form})



def postProfesor(request):
    if request.method == "POST":
        form = formProfesor(request.POST)
        if form.is_valid():
            info = form.cleaned_data
            nombre = info["nombre"]
            apellido = info["apellido"]
            email = info["email"]
            profesion = info["profesion"]
            profesor = Profesores(nombre=nombre, apellido=apellido, email=email, profesion=profesion)
            profesor.save()
            return redirect("AppEntrega:profesores")
        else:
            return render(request, "Appentrega/inicio.html", {"mensaje": "Error"})
    else:
        form = formProfesor()
    return render(request, "Appentrega/formularioProfe.html", {"formulario": form})


def postSocio(request):
    if request.method == "POST":
        form = formSocio(request.POST)
        if form.is_valid():
            info = form.cleaned_data
            nombre = info["nombre"]
            apellido = info["apellido"]
            dni = info["dni"]
            email = info["email"]
            socio = Socios(nombre=nombre, apellido=apellido, dni=dni, email=email)
            socio.save()
            return redirect("AppEntrega:socios")
        else:
            return render(request, "Appentrega/socios.html", {"mensaje": "Error"})
    else:
        form = formSocio()
    return render(request, "Appentrega/formularioSocio.html", {"formulario": form})

Entrega1/views.py
from django.http import HttpResponse
from django.template import loader

def home(request):

    template = loader.get_template('home.html')
    render = template.render()

    return HttpResponse(render)

AppEntrega/templates/Appentrega/deportes.html
{% extends '.\layout.html' %}

{% block main %}
<h1>Deportes</h1>

<div class="container p-4">
    <div class="container p-3 w-50">
        <form method="get" action="{% url 'AppEntrega:getDeporte' %}" class="mb-3">
            <div class="d-flex gap-2">
                <input type="text" class="form-control" id="inputDeporte" name="deporte" placeholder="Buscar deporte">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
        </form>
    </div>

    <hr>

    <div class="container d-flex">
        <div class="container p-4">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Deporte</th>
                        <th>Turno</th>
                        <th>Comisión</th>
                    </tr>
                </thead>
                <tbody>
                    {% for deporte in deportes %}
                    <tr>
                        <td>{{ deporte.nombre }}</td>
                        <td>{{ deporte.turno }}</td>
                        <td>{{ deporte.comision }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        <div class="container-sm px-5 w-50">
            <h4 class="p-2">Agregar deporte:</h4>
            <form action="{% url 'AppEntrega:deporteFormulario' %}" method="post">
                {% csrf_token %}
                <input type="text" name="nombre" placeholder="Nombre" class="form-control m-2">
                <input type="text" name="turno" placeholder="Turno (Mañana/Tarde/Noche)" class="form-control m-2">
                <input type="number" name="comision" placeholder="Comisión" class="form-control m-2"> 

                <button type="submit" class="btn btn-primary m-2">Agregar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

AppEntrega/templates/Appentrega/layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Entrega Uno</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body class="">
    
    {% include 'partials/navbar.html' %}

    {% if mensaje %}
      <div class="container d-flex justify-content-center p-4">
        <div class="w-50 alert alert-danger d-flex justify-content-center">
          <h4 class="m-0 fw-16">{{ mensaje }}</h4>
        </div>
      </div>
    {% endif %}

    <div class="container py-5">
        {% block main %}
        {% endblock %}
    </div>

    {% include 'partials/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

AppEntrega/templates/Appentrega/partials/footer.html
<footer class="text-center text-lg-start bg-light text-muted">
    <hr>
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <div class="row mt-3">
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>Club Atlético
                    </h6>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis soluta id modi dolorem, earum non necessitatibus voluptas totam quasi facilis suscipit sit distinctio! Perspiciatis provident veniam, voluptate totam ex tenetur.
                    </p>
                </div>

                <!-- 
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
        -->

                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <h6 class="text-uppercase fw-bold mb-4">Contacto</h6>
                    <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        info@example.com
                    </p>
                    <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                    <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
                </div>
            </div>
        </div>
    </section>

    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2022 Copyright:
        <a class="text-reset fw-bold" href="">clubatletico.com</a>
    </div>
</footer>
<!-- Footer -->

AppEntrega/templates/Appentrega/partials/mensaje.html
<div class="alert alert-success" role="alert">
    {{ mensaje }}
</div>

AppEntrega/templates/Appentrega/partials/navbar.html
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="{% url 'AppEntrega:inicio' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppEntrega:deportes' %}">Deportes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppEntrega:profesores' %}">Profesores</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppEntrega:socios' %}">Socios</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

AppEntrega/templates/Appentrega/profesores.html
{% extends '.\layout.html' %}

{% block main %}

<h1>Profesores</h1>

<div class="container d-flex">
    <div class="container p-4">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Profesión</th>
                </tr>
            </thead>
            <tbody>
                {% for profesor in profesores %}
                <tr>
                    <td>{{ profesor.nombre }}</td>
                    <td>{{ profesor.apellido }}</td>
                    <td>{{ profesor.email }}</td>
                    <td>{{ profesor.profesion }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="container-sm px-5 w-50">
        <h4 class="p-2">Agregar profesor:</h4>
        <form action="{% url 'AppEntrega:profeFormulario' %}" method="post">
            {% csrf_token %}
            <input type="text" name="nombre" placeholder="Nombre" class="form-control m-2">
            <input type="text" name="apellido" placeholder="Apellido" class="form-control m-2">
            <input type="email" name="email" placeholder="E-mail" class="form-control m-2"> 
            <input type="text" name="profesion" placeholder="Profesion" class="form-control m-2">

            <button type="submit" class="btn btn-primary m-2">Agregar</button>
        </form>
    </div>
</div>
{% endblock %}

AppEntrega/templates/Appentrega/socios.html
{% extends '.\layout.html' %}

{% block main %}

<h1>Socios</h1>

<div class="container d-flex">
    <div class="container p-4">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>DNI</th>
                </tr>
            </thead>
            <tbody>
                {% for socio in socios %}
                <tr>
                    <td>{{ socio.nombre }}</td>
                    <td>{{ socio.apellido }}</td>
                    <td>{{ socio.email }}</td>
                    <td>{{ socio.dni }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="container-sm px-5 w-50">
        <h4 class="p-2">Agregar socio:</h4>
        <form action="{% url 'AppEntrega:socioFormulario' %}" method="post">
            {% csrf_token %}
            <input type="text" name="nombre" placeholder="Nombre" class="form-control m-2">
            <input type="text" name="apellido" placeholder="Apellido" class="form-control m-2">
            <input type="number" name="dni" placeholder="DNI" class="form-control m-2">
            <input type="email" name="email" placeholder="E-mail" class="form-control m-2"> 

            <button type="submit" class="btn btn-primary m-2">Agregar</button>
        </form>
    </div>
</div>
{% endblock %}